### PR TITLE
Drivetrain stop when disabled

### LINKED ISSUE #44: Fix swerve coast/brake mode on disabled vs. teleoperated control.
Something weird was happening with enabling brake mode on disable today. The robot should be in brake when disabled such that the robot stops ASAP when disabling instead of coasting further.

### PR DESCRIPTION
**Pull request by Atman-Singh**
closes #44

### CODE REVIEW

**Review by MqxS — APPROVED** [review]
Looks like it should work.

**Comment by HarryXChen3** [comment]
This probably needs to be done differently, which is why it was never merged. We should not need to make a config call every time we enable/disable, they are blocking and take a non-negligible amount of time to send when compared to control requests (which I think the alternative solution uses?)

**Comment by HarryXChen3** [comment]
The logic does not work like that 💀 - the easiest way to fix it would be to just pass false to the `OverrideCoastDurNeutral` param on the normal control request we use during disable, and pass true when enabled. I just haven't thought much about it and there isn't a naive way to do it nicely.

**Comment by HarryXChen3** [comment]
Not sure why they were ever coast, actually. We're gonna leave them on brake mode at all times instead.

**Pull request closed without merging**
