### PR TITLE
Added to gitignore.

### PR DESCRIPTION
**Pull request by MqxS**

### CODE REVIEW

**Comment by HarryXChen3** [comment]
Are you sure this doesn't delete the `simgui.json` and `simgui-window.json` files locally? Or is it not a problem because they will be recreated by running simulation anyways?

**Review by HarryXChen3 — CHANGES_REQUESTED** [review]
See comment about deletion of the `.json` files.

**Comment by MqxS** [comment]
> Are you sure this doesn't delete the `simgui.json` and `simgui-window.json` files locally? Or is it not a problem because they will be recreated by running simulation anyways?

I manually deleted the files and added to the git ignore so they aren't on the repo at all. But I tested to make sure that they get recreated when you run sim and they do.

**Review by HarryXChen3 — APPROVED** [review]
Ok, just making sure. LGTM!

**Comment by MqxS** [comment]
closes #55

**Pull request merged**
